version: "2.3"
services:
  pytest-bdd_cli:
      build:
        context: .
        dockerfile: Dockerfile
      image: pytest-bdd_cli
      # entrypoint: pytest-bdd_cli.py
      # environment:
        # - AWS_SECURITY_TOKEN
      volumes:
        - ${PWD}:/app/input
